ep2_icaro/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('restaurants/', include('restaurants.urls')), # adicionar esta linha
    path('admin/', admin.site.urls),
]

restaurants/urls.py
from django.urls import path

from . import views

app_name = 'restaurants'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),  # edite esta linha
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'), # adicione esta linha
    path('search/', views.search_posts, name='search'), # adicione esta linha
    path('create/', views.PostCreateView.as_view(), name='create'), # adicione esta linha
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('categories<int:pk>', views.CategoryDetailView.as_view(), name='detail-category'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), # adicione esta linha
    path('', views.index, name='index'),
]

restaurants/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()  # Usando TextField para armazenar o conteúdo HTML
    poster_url = models.URLField(max_length=200, null=True)
    post_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title} ({self.post_date})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    post_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'
    
    
class Category(models.Model):
    name = models.CharField(max_length=255)
    content = content = models.TextField() 
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}'
    

restaurants/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'poster_url',
        ]
        labels = {
            'title': 'Título',
            'content': 'Conteúdo',
            'poster_url': 'URL do Poster',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Resenha',
        }

restaurants/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Post
from django.shortcuts import render, get_object_or_404
from .forms import PostForm
from django.views import generic
from django.urls import reverse_lazy
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm


class PostListView(generic.ListView):
    model = Post
    template_name = 'restaurants/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'restaurants/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post=self.object).order_by('-post_date')
        context['comment_form'] = CommentForm()
        return context

def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(title__icontains=search_term)
        context = {"post_list": post_list}
    return render(request, 'restaurants/search.html', context)

class PostCreateView(generic.CreateView):
    model = Post
    fields = ["title", "content", "poster_url"]
    template_name = 'restaurants/create.html'
    success_url = reverse_lazy('restaurants:index')

class PostUpdateView(generic.UpdateView):
    model = Post
    fields = ["title", "content", "poster_url"]
    template_name = 'restaurants/update.html'
    success_url = reverse_lazy('restaurants:index')

class PostDeleteView(generic.DeleteView):
    model = Post
    fields = ["title", "content", "poster_url"]
    template_name = 'restaurants/delete.html'
    success_url = reverse_lazy('restaurants:index')

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('restaurants:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'restaurants/comment.html', context)   

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'restaurants/categories.html' 

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'restaurants/detail_category.html'

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

restaurants/templates/restaurants/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de Restaurantes</h2>

<section class="lista-de-cards">
    {% for category in category_list %}
    <article class="card">
        <a href="{% url 'restaurants:detail-category' category.id %}"> <!-- modifique esta linha -->
            <p>{{ category.name }}</p>
        </a>
    </article>
    {% endfor %}
  </section>
{% endblock content %}

restaurants/templates/restaurants/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar sobre o Restaurante {{ post.name }}</h2>

<form action="{% url 'restaurants:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'restaurants:detail' post.id %}">Voltar para a página do restaurante</a></p>
{% endblock content %}

restaurants/templates/restaurants/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Restaurante</h2>
<form method="post" action="{% url 'restaurants:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

restaurants/templates/restaurants/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'restaurants:delete' post.id %}" method="post">
  {% csrf_token %}
  <p>
    Você tem certeza que deseja apagar o restaurante "{{ post.title }}"?
  </p>
  <button type="submit">Apagar</button>
</form>
{% endblock content %}

restaurants/templates/restaurants/detail.html
{% extends 'base.html' %} {% block title %} {{ post.title }} {% endblock title %} {% block content %}
<h2>Detalhes do Restaurante {{ post.title }}</h2>

<section class="dados-de-filme">
  <img src="{{ post.poster_url }}" alt="Foto do Restaurante {{ post.title}}" />
  <ul>
    <li><strong>Nome:</strong> {{ post.title }}</li>
    <hr>
    <li><strong>Descrição:</strong> {{ post.content }}</li>
    <hr>
    <li><strong>Data de Postagem:</strong> {{ post.post_date }}</li>
    <hr>
    {% if post.category_set.all %}
    <li>Incluso nas categorias:
        <p> {% for category in post.category_set.all %}
                <a href="{% url 'restaurants:detail-category' category.id %}">{{ category.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
    </li>
    <hr>
{% endif %}
    <br>
    <li><a href="{% url 'restaurants:update' post.id %}">Editar</a></li>
    <li><a href="{% url 'restaurants:delete' post.id %}">Apagar</a></li>
  </ul>
  <hr>
</section>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>    
        {% if comments %}
            {% for comment in comments %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }}  [{{ comment.post_date }}]</figcaption>
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário sobre este restaurante.</p>
        {% endif %}
    </ul>
    <hr>

    <a href="{% url 'restaurants:comment' post.pk %}"><button>Crie sua Resenha</button></a>
</section>

{% endblock content %}

restaurants/templates/restaurants/detail_category.html
{% extends 'base.html' %} {% block title %} {{ post.title }} {% endblock title %} {% block content %}
<h2>Restaurantes da Categoria {{ post.title }}</h2>

  <ul>
    <li><strong>Nome:</strong> {{ category.name }}</li>
    <hr>
    <li><strong>Descrição:</strong> {{ category.content }}</li>
<hr>

{% if category.posts.all %}
<section class="lista-de-cards">
    {% for post in category.posts.all %}
    <article class="card">
      <a href="{% url 'restaurants:detail' post.id %}"> <!-- modifique esta linha -->
          <img src="{{ post.poster_url }}" alt="Foto do Restaurante {{ post.title }}" />
      </a>
      <p>{{ post.title }}</p>
    </article>
    {% endfor %}
  </section>
  {% else %}
  <p>Não foi encontrado nenhum restaurante.</p>
  {% endif %} {% endblock content %}

restaurants/templates/restaurants/index.html
{% extends 'base.html' %} {% block content %}
<h2>Todos os Restaurantes</h2>
<section>
  <p>
    Muitos resultados? <a href="{% url 'restaurants:search' %}">Buscar Restaurantes</a>
  </p>
  <p>
    Não encontrou o restaurante?
    <a href="{% url 'restaurants:create' %}">Adicionar Novo Restaurante</a>
  </p>
</section>
{% if post_list %}

<section class="lista-de-cards">
  {% for post in post_list %}
  <article class="card">
    <a href="{% url 'restaurants:detail' post.id %}"> <!-- modifique esta linha -->
        <img src="{{ post.poster_url }}" alt="Foto do Restaurante {{ post.title }}" />
    </a>
    <p>{{ post.title }}</p>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum restaurante.</p>
{% endif %} {% endblock content %}

restaurants/templates/restaurants/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Restaurantes por Nome</h2>
<form action="{% url 'restaurants:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <img src="{{ post.poster_url }}" alt="Foto do Restaurante {{ post.title }}">
        <p>{{ post.title }}</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum Restaurante para a busca.</p>
{% endif %}

{% endblock content %}

restaurants/templates/restaurants/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Restaurante {{ post.title }}</h2>
<form method="POST" action="{% url 'restaurants:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Hunger Places
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="https://i.imgur.com/N4vMwE2.png" width="200px" height="200px"> <!-- adicione esta linha -->
            <nav id="navegacao-principal">
                <ul>
                  <li><a href="{% url 'restaurants:index' %}">Restaurantes</a></li>
                  <li><a href="{% url 'restaurants:categories' %}">Categorias</a></li> <!-- adicionar esta linha -->
                  <li><a href="{% url 'about' %}">Sobre</a></li>
                </ul>
              </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2023</small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
<p>Esse site tem como objetivo reunir informações sobre os melhores restaurantes de São Paulo. Sejam bem-vindos, e fiquem à vontade para conhecer novos locais e novas experiências gastronômicas</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Hunger Places</i></h1>
<p>A página para a galera que gosta de comer bem!</p>
{% endblock content %}